--
-- Database: `bedita2`

-- --------------------------------------------------------
TRUNCATE TABLE `links`;
TRUNCATE TABLE `documents`;
TRUNCATE TABLE `books`;
TRUNCATE TABLE `event_date_items`;
TRUNCATE TABLE `events`;
TRUNCATE TABLE `object_users`;
TRUNCATE TABLE `bibliographies`;
TRUNCATE TABLE `base_documents`;
TRUNCATE TABLE `content_bases_objects`;
TRUNCATE TABLE `contents_typed_object_categories`;
TRUNCATE TABLE `contents`;
TRUNCATE TABLE `authors`;
TRUNCATE TABLE `images`;
TRUNCATE TABLE `files`;
TRUNCATE TABLE `typed_object_categories`;
TRUNCATE TABLE `answers`;
TRUNCATE TABLE `faq_questions`;
TRUNCATE TABLE `audio_videos`;
TRUNCATE TABLE `areas`;
TRUNCATE TABLE `streams`;
TRUNCATE TABLE `short_news`;
TRUNCATE TABLE `newsletters`;
TRUNCATE TABLE `lang_texts`;
TRUNCATE TABLE `indexs`;
TRUNCATE TABLE `permissions`;
TRUNCATE TABLE `object_users`;
TRUNCATE TABLE `questions`;
TRUNCATE TABLE `versions`;
TRUNCATE TABLE `trees`;
TRUNCATE TABLE `comments`;
TRUNCATE TABLE `biblio_items`;
TRUNCATE TABLE `content_bases`;
TRUNCATE TABLE `custom_properties`;
TRUNCATE TABLE `collections`;
TRUNCATE TABLE `objects`;
TRUNCATE TABLE `question_types`;
TRUNCATE TABLE `object_types`;
TRUNCATE TABLE `groups_users`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `groups`;
TRUNCATE TABLE `permission_modules`;
TRUNCATE TABLE `modules`;
