build:
    environment:
        php: "7.4"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
  php: true

filter:
  paths:
    - 'src/*'
    - 'plugins/BEdita/API/src/*'
    - 'plugins/BEdita/Core/src/*'
  dependency_paths:
    - 'vendor/*'
