#!/usr/bin/env ruby

root_dir="./bedita"
tmp_dir="./tmp"

svn="https://svn.channelweb.it/bedita/trunk/bedita-app"
svnuser="raf"
svnpass="cw"

namespace :init do
  cake_path = File.join(root_dir, "lib")
  beditaapp_path = File.join(root_dir, "lib", "BEdita")  

  desc 'make root directory tree'
  task :mkdirs do
    if not File.exists?(root_dir) then
      puts "mkdir #{Dir.getwd}/#{root_dir}"
      Dir.mkdir(root_dir)
      puts "mkdir #{tmp_dir}"
      Dir.mkdir(tmp_dir)
      
      %w{lib instances apache svn}.each do |rootsubdir|
        puts "mkdir #{File.join(root_dir, rootsubdir)}"
        Dir.mkdir(File.join(root_dir, rootsubdir))
      end
    else
      puts "#{root_dir} exists"
    end
  end
  
  desc 'download cake'
  task :download_cake do
    cake_ver="cake_1.1.18.5850"
    cake_url="http://cakeforge.org/frs/download.php/548/#{cake_ver}.tar.gz/donation=complete"
    
    %x{ curl -o #{ File.join(tmp_dir, "cake.tar.gz") } #{cake_url} }
    %x{ cd #{tmp_dir}; tar zxvf cake.tar.gz }
    %x{ mv #{File.join(tmp_dir, cake_ver, "cake")} #{cake_path} }
  end
  
  desc 'checkout bedita app'
  task :checkout_bedita do
    %x{ svn co --username=#{svnuser} --password=#{svnpass} #{svn} #{beditaapp_path} }
  end
  
  desc 'show bedita release version'
  task :version_bedita do
    puts %x{svn info #{beditaapp_path} | egrep '(Revision|Date)'}
  end
  
  desc 'update bedita'
  task :update_bedita do
    puts %x{svn --username=#{svnuser} --password=#{svnpass} up #{beditaapp_path} }
  end

end

namespace :instances do
  
  desc 'create new instance'
  task :new do
  end

  desc 'create instance db'
  task :createdb do
  end

  desc 'list available instances'
  task :list do
  end
  
  desc 'apache config'
  task :apache do
  end
  
end     

desc "clear all"
task :clear do
   system('rm -fr ./bedita; rm -fr ./tmp')
end
